services:
  minio:
    image: minio/minio:RELEASE.2024-07-26T20-48-21Z
    hostname: coms-minio
    container_name: coms-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --console-address ":9001" /data
    networks:
      - coms-network
networks:
  dbms-network:
    name: coms-network
    external: true